# Generated by Django 5.1.8 on 2025-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_im_backend", "0005_alter_mealentry_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tutorial_completed",
            field=models.BooleanField(default=False),
        ),
    ]
