services:
  insumate:
    container_name: insumate
    image: jcivitell/insumate:latest
    restart: always
    environment:
      SECRET_KEY: django-insecure-tlic@!^@d_+jmo7=n&^&y1n1*w9i=00b+u$r!lzos%jdkuk&&u
      ALLOWED_HOSTS: '*'
      MAIN_DATABASE_HOST: insumate_mariadb
      MAIN_DATABASE_NAME: insumate
      MAIN_DATABASE_USER: insumate
      MAIN_DATABASE_PASSWD: insumatepw
      MAIN_DATABASE_ENGINE: django.db.backends.mysql
      REDIS_HOST: insumate_redis
    depends_on:
      insumate_mariadb:
        condition: service_healthy
      insumate_redis:
        condition: service_started

  insumate_mariadb:
    container_name: insumate_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: insumate
      MARIADB_PASSWORD: insumatepw
      MARIADB_DATABASE: insumate
      MARIADB_ROOT_PASSWORD: megasec
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql:/var/lib/mysql

  insumate_redis:
    container_name: insumate_redis
    image: redis:latest
    restart: always

  nginx:
    container_name: insumate_nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - insumate
    ports:
      - "80:80"